#SimulationSettings
#Thu Jun 11 18:07:25 CEST 2026
fragments=true
lastDirectory=/home/xenixso/IdeaProjects/mergingmyself/ManhattanProject/app
resolution=1920x1080
windowHeight=1010
windowWidth=1920
windowX=0
windowY=0
